// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx7c3EB_lD1ydzwfiCAIkgFgCTvZ-Dh9Q',
    appId: '1:57053569309:android:cfac691ed0486212ab81f4',
    messagingSenderId: '57053569309',
    projectId: 'fir-chat-app-7879e',
    storageBucket: 'fir-chat-app-7879e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmdtLSkzKo1vjjD4IZpaQJd3H-yltnPqc',
    appId: '1:57053569309:ios:142ed1128d789c3aab81f4',
    messagingSenderId: '57053569309',
    projectId: 'fir-chat-app-7879e',
    storageBucket: 'fir-chat-app-7879e.appspot.com',
    iosBundleId: 'com.example.panchatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmdtLSkzKo1vjjD4IZpaQJd3H-yltnPqc',
    appId: '1:57053569309:ios:142ed1128d789c3aab81f4',
    messagingSenderId: '57053569309',
    projectId: 'fir-chat-app-7879e',
    storageBucket: 'fir-chat-app-7879e.appspot.com',
    iosBundleId: 'com.example.panchatapp',
  );

}